export const RECENT_SEARCHES_LOCAL_STORAGE_KEY = 'RECENT_SEARCHES_LOCAL_STORAGE_KEY';
export const GEOLOCATION_SEARCHES_LOCAL_STORAGE_KEY = 'GEOLOCATION_SEARCHES_LOCAL_STORAGE_KEY';
export const APARTMENTS_LOCAL_STORAGE_KEY = 'APARTMENTS_LOCAL_STORAGE_KEY';
